name = "phneakngar-ws-do"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 0.1

[observability.logs]
invocation_logs = true
head_sampling_rate = 0.1

[observability.traces]
enabled = true
head_sampling_rate = 0.05

[dev]
port = 15212
inspector_port = 9233

[[d1_databases]]
binding = "DB"
database_id = "45d8f476-3631-47fb-abd1-49659a6234fe"
database_name = "phneakngar-app"

[[durable_objects.bindings]]
name = "WS_DO"
class_name = "WebSocketDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketDurableObject"]
