packages:
  - "src/shared"
  - "src/cli"
  - "src/web"
  - "src/email-worker"
  - "src/ws-do"
  - "src/app"
  - "src/desktop"
  - "tests/utils"

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - msw
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
patchedDependencies:
  '@base-ui/react@1.6.0': patches/@base-ui__react@1.6.0.patch
