export const EMAIL_LABELS = {
  compose: {
    title: "អ៊ីមែលថ្មី",
    discard: "បោះបង់",
    send: "ផ្ញើ",
    from: "ពី",
    to: "ទៅ",
    subject: "ប្រធានបទ",
    subjectPlaceholder: "ប្រធានបទអ៊ីមែល",
    bodyPlaceholder: "សរសេរអ៊ីមែលរបស់អ្នក...",
    attachFile: "ភ្ជាប់ឯកសារ",
    uploadFailed: "ផ្ទុកឯកសារភ្ជាប់មិនបាន",
    fileTooLarge: (filename: string) => `${filename} លើសកំណត់ 10 MB`,
  },
  toolbar: {
    bold: "ដិត",
    italic: "ទ្រេត",
    underline: "គូសបន្ទាត់ក្រោម",
    strikethrough: "គូសបន្ទាត់កាត់",
    heading1: "ចំណងជើង 1",
    heading2: "ចំណងជើង 2",
    bulletList: "បញ្ជីចំណុច",
    orderedList: "បញ្ជីលេខរៀង",
    alignLeft: "តម្រឹមឆ្វេង",
    alignCenter: "តម្រឹមកណ្តាល",
    alignRight: "តម្រឹមស្តាំ",
    insertLink: "បញ្ចូលតំណ",
    removeLink: "ដកតំណ",
    insertImage: "បញ្ចូលរូបភាព",
    horizontalRule: "បន្ទាត់ផ្តេក",
    validUrl: "សូមបញ្ចូល URL ត្រឹមត្រូវ",
    displayText: "អត្ថបទបង្ហាញ",
    insert: "បញ្ចូល",
  },
} as const;
